# Generated by Django 6.0.1 on 2026-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Draft", "Published")],
                default="Draft",
                max_length=20,
            ),
        ),
    ]
